### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by TimK50** [MSCMP/MSCMP#12]
When I compile MSCMPMessages it writes error with LightSwitchInitMessage. How fix it? Sorry for my bad English

**Comment by CurtisVL** [comment]
Hi,
A pull request has been made to fix this issue.

If you are trying to play the mod, rather than develop it, there is some builds you can download from:
http://www.mysummercar.mp/p/download.html

**Comment by norbert79** [comment]
Main problem with the download link is, that while in Jenkins I am able to see if there has been any new release of the compiled code, or not while using the download link I am just offered the setup with some random numbers. I would suggest using either version/build numbers as filename or at least some indication if there has been any update, like using the date as filename.

**Comment by CurtisVL** [comment]
There will be a 'proper' versioning system, it just hasn't been implemented yet. Sorry. :)

**Comment by CurtisVL** [comment]
This issue is now resolved.
