### ISSUE TITLE
Failed to run multiplayer mod

### ISSUE THREAD

**Issue by Extar93** [MSCMP/MSCMP#15]
After assembling all the parts, when starting the mod, an error "Failed to run multiplayer mod!" Is issued, the re-assembly does not help. How to fix this error?

**Comment by CurtisVL** [comment]
Hey, if you were looking to simply play the mod rather than develop it, there's a download on the website. :)

**Comment by CurtisVL** [comment]
If you were looking to contribute to the mod, just reply back and I'll see if I can help with that error.

**Comment by CurtisVL** [comment]
Are you are you made the Unity asset bundle? Without that it won't run. :)

**Comment by Extar93** [comment]
I performed in the MSCMP > Build Asset Bundles.., There were warnings, but everything was going well. Maybe it's them?

**Comment by RootKiller** [comment]
@Extar93 did you solved the problem?

**Comment by Extar93** [comment]
@RootKiller No.

**Comment by RootKiller** [comment]
Please try with latest master.
