### ISSUE TITLE
Items Disappearing

### ISSUE THREAD

**Issue by byBlurr** [MSCMP/MSCMP#16]
Me and a couple mates have been experiencing an issue with the default items at the start disappearing when we go into a multiplayer game. It is only the default items in the garage.

**Comment by byBlurr** [comment]
When looking into this, we come to realise it also duplicated items that were already installed in the car.

**Comment by RootKiller** [comment]
@byBlurr we need you to retest it on 0.2.5 release. You can download it from http://www.mysummercar.mp/p/download.html also if the bug still occurs please provide some video. Thanks!
