### ISSUE TITLE
Wasp nest in Ruscko not synced?

### ISSUE THREAD

**Issue by scrpiit** [MSCMP/MSCMP#18]
Only the host can kill the nest in the Ruscko. Either with dipping it in water or fire extinguisher.
While the nest remains unkillable for the remote player.

**Comment by RootKiller** [comment]
Yup not synchronized.

**Comment by VLHosting** [comment]
Should be synced in the next update. 👍

**Comment by CurtisVL** [comment]
Should be synced in the next update. 👍
