### ISSUE TITLE
Weird texture when starting

### ISSUE THREAD

**Issue by epiyolo** [MSCMP/MSCMP#19]
Everytime I launch MSCMP, I am greeted to only half of textures on warning screen and main menu, as well as the entire game itself. pls fix

**Comment by RootKiller** [comment]
Can you reproduce this in single player?

**Comment by epiyolo** [comment]
What do you mean?

**Comment by RootKiller** [comment]
Any update @epiyolo?

**Comment by CurtisVL** [comment]
Unable to reproduce and no response from original poster, closing issue. :)
