### ISSUE TITLE
Moped not working, crash when picking up shopping bag.

### ISSUE THREAD

**Issue by suomilanittaja** [MSCMP/MSCMP#22]
moped is not working.
game crash when i pickup shopping bag.

**Comment by RootKiller** [comment]
@DarkKostas @VLHosting do we know something about "moped is not working."?

**Comment by RootKiller** [comment]
@suomilanittaja next time please create separate issue for each bug.

**Comment by DarkKostas** [comment]
Not really. Moped is working fine for me. Can you explain what exactly is your problem? Do you get a crash, can't you start it or what.

**Comment by CurtisVL** [comment]
The issue with the shopping bag causing crashes is due to sync of it not yet being implemented; That will come in a future version of the mod.
As for the moped, as @DarkKostas said, you need to provide us with more details.

**Comment by CurtisVL** [comment]
Both issues are resolved in 0.3.
