### ISSUE TITLE
Game crashes when trying to drink bear

### ISSUE THREAD

**Issue by rawdom** [MSCMP/MSCMP#24]
When trying to drink a beer whom ever is the other person is, they will crash. Happens if client or host.

**Comment by rawdom** [comment]
Did another test, only when in sight of the other player this happens

**Comment by DarkKostas** [comment]
The other player is always rendered, so i am not sure what you mean by only if you're in sight. Also it would be nice to post a crash log as we had tried drinking ourselves and never had any issues.

**Comment by rawdom** [comment]
I did some more investigating, although I could not find the crash log I looked at my network log and noticed I had packet errors. I'm just going to assume that is what caused it.
