### ISSUE TITLE
Tried to pickup not network pickupable

### ISSUE THREAD

**Issue by SAMURAIHANDBRAKE** [MSCMP/MSCMP#31]
When im pick up details from suspension or lights, game has crashed, How can i fix this?

**Comment by IvovdBruggen** [comment]
I'm getting the same issue after I spawn the envelope, but the game only crashes as soon as I pick up the envelope. When my friend tries it in the same lobby it also happens. I think if you follow these steps it should be reproducible.

**Comment by CurtisVL** [comment]
This issue was resolved in 0.3.
