### ISSUE TITLE
0.3 ne zaman

### ISSUE THREAD

**Issue by furkan0972** [MSCMP/MSCMP#37]
yeni güncelleme ne zaman gelecek ve güncellemelerde neleri düzeltecekler? teşekürler...

**Comment by Trexitr** [comment]
Belli değil ama büyük güncelleme gelecek deniliyor. Birçok buglar düzeltilecek yeni özellik getirilmeyecek dahada oynanabilir bi hale getirilmeyi planlıyolar.

**Comment by RootKiller** [comment]
Hi, please use english. We do not provide Turkish support.
