### ISSUE TITLE
Open source errors ?

### ISSUE THREAD

**Issue by Scozor** [MSCMP/MSCMP#38]
Hello, I am having problems concerning the installation of the sources to program. I was told to contact you because I receive errors while I followed the steps.

UnityEngine, AssetBundle, Steamworks, and others are not referenced.
I also have an error: src \ MSCMPClient \ Network \ NetMessages.generated.cs' is not found.

Sorry for my English

**Comment by RootKiller** [comment]
You have to run `setup.bat`. Read the readme file of repository there is a guide what steps you have to make.

**Comment by Scozor** [comment]
Already done
