### ISSUE TITLE
Unity Log Error

### ISSUE THREAD

**Issue by SQLMNC** [MSCMP/MSCMP#39]
Whenever I launch the setup, I don't know what to do, so I just click "Next" and then "Install". I then tick "Launch MSCMP" and click "Finish". An error suddenly appears saying "Unable to create Unity Log!" and the only thing I can do is press "Ok" and it goes away. What do I do?

**Comment by andreynewell** [comment]
Run MSCMP as Admin

**Comment by RootKiller** [comment]
This have been fixed in https://github.com/MSCMP/MSCMP/commit/ee255d2d8850dd4a04d04942ce47a7d18957c7d1.
