### ISSUE TITLE
Weather sync packet gets delivered before game start causing null access.

### ISSUE THREAD

**Issue by Bamdierise** [MSCMP/MSCMP#40]
So this Fatal Error happens when im trying to join my friend.
![offers](https://user-images.githubusercontent.com/44462497/47487198-a7407900-d84a-11e8-8189-b65510d87a31.PNG)

**Comment by andreynewell** [comment]
![image](https://user-images.githubusercontent.com/44510558/47590500-1a460e80-d975-11e8-9159-676e73c987b9.png)

**Comment by RootKiller** [comment]
The problem is that the packet could be delivered a frame before game actually collects weather script causing this error. This has to be rewritten to properly set weather state after game starts.

**Comment by CurtisVL** [comment]
This is finally resolved! Woooo!
I re-wrote weather sync, though you'll need to download the latest dev build from within our Discord server to get this. 👍
