### ISSUE TITLE
Unable to create unity log

### ISSUE THREAD

**Issue by SteelingSword94** [MSCMP/MSCMP#41]
I have attempted on getting the my summer car multiplayer and upon launching it i get a error "Unable to create unity log"

Could someone please help me out with this thank you.

**Comment by kinecty** [comment]
Have the same issue /\

**Comment by kinkkukiusaus** [comment]
Run MSCMP as administrator. It worked for me.

**Comment by CurtisVL** [comment]
This issue should be resolved in the latest build. Please join our Discord server to check out experimental new features and have the latest bug-fixes!
