### ISSUE TITLE
Failed to initialize steam

### ISSUE THREAD

**Issue by SkyCZ** [MSCMP/MSCMP#46]
![image](https://user-images.githubusercontent.com/34968650/50562499-9ada1000-0d14-11e9-9fad-1200a8197219.png)
Im using older version of steam becouse i hate the new steam chat...

**Comment by RootKiller** [comment]
Hello. Please try to run MSCMP as admin.

**Comment by CurtisVL** [comment]
Please try using the latest dev build available for download from within our Discord server, or try updating your Steam client if the issue is not resolved!
