### ISSUE TITLE
Hello. Please try to run MSCMP as admin.

### ISSUE THREAD

**Issue by b2uno1** [MSCMP/MSCMP#56]
Hello. Please try to run MSCMP as admin.

_Originally posted by @RootKiller in https://github.com/MSCMP/MSCMP/issues/46#issuecomment-456442753_

**Comment by CurtisVL** [comment]
The mod should work correctly when run as admin or not, please join our Discord server and try out the latest experimental build of the mod as running as admin should now be resolved.
