### ISSUE TITLE
Crash when other players enter vehicles

### ISSUE THREAD

**Issue by ItsiAdam** [MSCMP/MSCMP#9]
The game crashes immediately when another player enters a vehicle.
Here's a screenshot of the error: https://i.imgur.com/kEaPcF7.png

**Comment by CurtisVL** [comment]
Which vehicle were both players in when this occurred?
I've spent most of today entering and leaving vehicles whilst working on vehicle engine sync, but I've yet to have this crash.

**Comment by RootKiller** [comment]
The only place this error can happen is:

```csharp
		public void SetPlayer(NetPlayer player, bool passenger) {
			if (passenger) {
				passengerPlayer = player;
			}
			else {
				driverPlayer = player;

				bool remoteSteering = (driverPlayer != null) && !(driverPlayer is NetLocalPlayer);
				>>> GameObject.SetRemoteSteering(remoteSteering);
			}
		}
```

**Comment by J28B** [comment]
When It was in my story, I invited adam here and got into the blue van. Every time I went into driving mode it just crashed him every time.

**Comment by CurtisVL** [comment]
Make sure you both have the same game version, and mod version.
I'm still unable to reproduce this issue.

**Comment by J28B** [comment]
He had a fresh install and so did I of both the game and the mod.

**Comment by RootKiller** [comment]
Yo can you retest this with 0.2.5 (http://www.mysummercar.mp/p/download.html) please? @ItsiAdam @J28B

**Comment by J28B** [comment]
Yeah sure we can probably try it soon enough.

**Comment by ItsiAdam** [comment]
Yep we can probably try it soon
